/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIP5;

/**
 *
 * @author zanke
 */
public class PenjualanRumahForm extends javax.swing.JFrame {

    /**
     * Creates new form PenjualanRumahForm
     */
    public PenjualanRumahForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtHargaTanah = new javax.swing.JTextField();
        txtLuasTersedia = new javax.swing.JTextField();
        txtHargaBangunan = new javax.swing.JTextField();
        txtLuasAsli = new javax.swing.JTextField();
        cbArea = new javax.swing.JComboBox<>();
        rbTipe36 = new javax.swing.JRadioButton();
        rbTipe49 = new javax.swing.JRadioButton();
        rbTipe90 = new javax.swing.JRadioButton();
        btnSimpan = new javax.swing.JButton();
        btnProses = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        txtDP = new javax.swing.JTextField();
        txtCicilan = new javax.swing.JTextField();
        txtCicilanBulan = new javax.swing.JTextField();
        txtPPN = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Decisiontree = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("HargaTanah");

        jLabel3.setText("Area");

        jLabel4.setText("Harga Bangunan");

        jLabel5.setText("Tipe Rumah");

        jLabel6.setText("LuasTanah");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        txtLuasTersedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuasTersediaActionPerformed(evt);
            }
        });

        txtHargaBangunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaBangunanActionPerformed(evt);
            }
        });

        cbArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bougenvile", "Melati", "Flamboyan" }));
        cbArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAreaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTipe36);
        rbTipe36.setText("Tipe-16");
        rbTipe36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTipe36ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTipe49);
        rbTipe49.setText("Tipe-09");
        rbTipe49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTipe49ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTipe90);
        rbTipe90.setText("Tipe-05");
        rbTipe90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTipe90ActionPerformed(evt);
            }
        });

        btnSimpan.setText("simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        btnClear.setText("clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel7.setText("Luas Tersedia");

        jLabel8.setText("Harga");

        jLabel9.setText("Dp");

        jLabel10.setText("Lama cicilan");

        jLabel11.setText("ppn10%");

        jLabel12.setText("Cicilan/bln");

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        txtDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDPActionPerformed(evt);
            }
        });

        txtCicilanBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCicilanBulanActionPerformed(evt);
            }
        });

        txtPPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPPNActionPerformed(evt);
            }
        });

        jLabel13.setText("bln");

        Decisiontree.setText("Decisiontree");
        Decisiontree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecisiontreeActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIP5/c17129b2d2cd45e4d928c058b6b46665_0.jpeg"))); // NOI18N
        jLabel14.setText("jLabel14");

        jMenu1.setText("File");

        jMenuItem1.setText("Login");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("exit");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pilihan");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("PenjualanRumah");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("TampilanData");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(81, 81, 81))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtHargaTanah, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNama))
                                .addGap(16, 16, 16))))
                    .addComponent(jLabel2)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(txtHargaBangunan, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(rbTipe36)
                            .addComponent(rbTipe49))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtLuasTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtLuasAsli, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPPN)
                                    .addComponent(txtCicilanBulan)
                                    .addComponent(txtCicilan)
                                    .addComponent(txtDP)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Decisiontree)
                                .addGap(45, 45, 45)
                                .addComponent(btnProses)
                                .addGap(33, 33, 33)
                                .addComponent(btnSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btnClear))))
                    .addComponent(rbTipe90))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHargaBangunan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtHargaTanah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(2, 2, 2)
                        .addComponent(txtLuasAsli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbTipe36)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbTipe49)
                            .addComponent(txtLuasTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(rbTipe90)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCicilanBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnProses)
                    .addComponent(btnClear)
                    .addComponent(Decisiontree))
                .addContainerGap(566, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void rbTipe36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTipe36ActionPerformed
                                       
    txtLuasAsli.setText("90"); // Contoh luas tanah asli Tipe 36
    txtHargaBangunan.setText("90000000"); // Contoh harga bangunan 90 juta
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTipe36ActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
try {            // 1. Mengambil data dari TextField dan mengubahnya jadi angka
            double luasTersedia = Double.parseDouble(txtLuasTersedia.getText());
            double hargaTanahPerM2 = Double.parseDouble(txtHargaTanah.getText());
            double hargaBangunan = Double.parseDouble(txtHargaBangunan.getText());
            double dp = Double.parseDouble(txtDP.getText());
            int lamaCicilan = Integer.parseInt(txtCicilan.getText()); // txtCicilan adalah lama cicilan

            // 2. Rumus Hitungan
            double hargaTotal = (luasTersedia * hargaTanahPerM2) + hargaBangunan;
            double ppn = 0.10 * hargaTotal;
            double cicilanBulan = (hargaTotal + ppn - dp) / lamaCicilan;

            // 3. Menampilkan hasil perhitungan kembali ke Form
            txtHarga.setText(String.valueOf(hargaTotal));
            txtPPN.setText(String.valueOf(ppn));
            txtCicilanBulan.setText(String.valueOf(cicilanBulan)); // Ini yang benar, bukan txtCicilan

            // 4. Memunculkan kotak konfirmasi
            javax.swing.JOptionPane.showMessageDialog(this, "PELANGGAN KONFIRM/SETUJU");

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pastikan semua data angka telah diisi dengan benar!", "Error Input", javax.swing.JOptionPane.ERROR_MESSAGE);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
                                         
    // Mengosongkan semua text field
    txtNama.setText("");
    txtHargaTanah.setText("");
    txtHargaBangunan.setText("");
    txtLuasAsli.setText("");
    txtLuasTersedia.setText("");
    txtDP.setText("");
    txtCicilan.setText("");
    txtHarga.setText("");
    txtPPN.setText("");
    txtCicilanBulan.setText("");
    
    // Mengembalikan combobox ke pilihan pertama
    cbArea.setSelectedIndex(0);
    
    // Menghilangkan pilihan radio button
    buttonGroup1.clearSelection();
    
    // Mengembalikan kursor ke kolom Nama
    txtNama.requestFocus();
      // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    try {
    // 1. Memanggil koneksi yang sudah kita buat di TestKoneksi / class Koneksi
    // Pastikan memanggil nama class koneksi yang benar, misalnya pertemuan_8.TestKoneksi.getKoneksi() 
    // jika Anda menambahkan method getKoneksi() di sana. Jika Anda buat class terpisah bernama Koneksi, gunakan Koneksi.getKoneksi()
    java.sql.Connection cn = koneksi.getKoneksi(); 
    
    // 2. Perintah SQL INSERT (11 tanda tanya karena ada 11 kolom di tabel)
    String sql = "INSERT INTO jual_rumah (nama_pemesan, area, harga_tanah, harga_bangunan, tipe_rumah, luas_tanah, harga_total, dp, lama_cicilan, ppn, cicilan_perbulan) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
    
    java.sql.PreparedStatement pStat = cn.prepareStatement(sql);
    
    // 3. Menentukan Tipe Rumah dari RadioButton yang dipilih
    String tipe = "";
    if (rbTipe36.isSelected()) {
        tipe = "Tipe-36";
    } else if (rbTipe49.isSelected()) {
        tipe = "Tipe-49";
    } else if (rbTipe90.isSelected()) {
        tipe = "Tipe-90";
    }

    // 4. Mengisi nilai parameter (?,?,?) dengan data dari Form
    pStat.setString(1, txtNama.getText());
    pStat.setString(2, cbArea.getSelectedItem().toString());
    pStat.setDouble(3, Double.parseDouble(txtHargaTanah.getText()));
    pStat.setDouble(4, Double.parseDouble(txtHargaBangunan.getText()));
    pStat.setString(5, tipe);
    pStat.setInt(6, Integer.parseInt(txtLuasAsli.getText()));
    pStat.setDouble(7, Double.parseDouble(txtHarga.getText()));
    pStat.setDouble(8, Double.parseDouble(txtDP.getText()));
    pStat.setInt(9, Integer.parseInt(txtCicilan.getText()));
    pStat.setDouble(10, Double.parseDouble(txtPPN.getText()));
    pStat.setDouble(11, Double.parseDouble(txtCicilanBulan.getText()));
    
    // 5. Eksekusi penyimpanan ke MySQL
    pStat.executeUpdate();
    
    javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan ke Database MySQL!");
    
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Gagal Simpan: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtHargaBangunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaBangunanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaBangunanActionPerformed

    private void txtLuasTersediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuasTersediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuasTersediaActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
 // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // Memanggil form PenjualanRumahForm agar muncul di layar
        PenjualanRumahForm jual = new PenjualanRumahForm();
        jual.setVisible(true);
        jual.setLocationRelativeTo(null); // Agar muncul di tengah layar        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TampianDataForm tampil = new TampianDataForm();
        // Menampilkan form tersebut ke layar
        tampil.setVisible(true);
        // Opsional: Mengatur agar form muncul tepat di tengah layar
        tampil.setLocationRelativeTo(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void txtDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDPActionPerformed

    private void txtPPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPPNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPPNActionPerformed

    private void txtCicilanBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCicilanBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCicilanBulanActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void cbAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAreaActionPerformed
                                     
    // Mengecek area apa yang dipilih, lalu memunculkan harga tanahnya
    if (cbArea.getSelectedItem().equals("Bougenvile")) {
        txtHargaTanah.setText("500000"); // Contoh harga 500rb/m2
    } else if (cbArea.getSelectedItem().equals("Melati")) {
        txtHargaTanah.setText("600000"); // Contoh harga 600rb/m2
    } else if (cbArea.getSelectedItem().equals("Flamboyan")) {
        txtHargaTanah.setText("700000"); // Contoh harga 700rb/m2
    } else {
        txtHargaTanah.setText(""); 
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAreaActionPerformed

    private void rbTipe49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTipe49ActionPerformed
    txtLuasAsli.setText("120"); // Contoh luas
    txtHargaBangunan.setText("120000000");        // TODO add your handling code here:
    }//GEN-LAST:event_rbTipe49ActionPerformed

    private void rbTipe90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTipe90ActionPerformed
    txtLuasAsli.setText("150"); // Contoh luas
    txtHargaBangunan.setText("150000000");        // TODO add your handling code here:
    }//GEN-LAST:event_rbTipe90ActionPerformed

    private void DecisiontreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecisiontreeActionPerformed
   try {
        // ambil data input
        double luasTersedia = Double.parseDouble(txtLuasTersedia.getText());
        double hargaTanahPerM2 = Double.parseDouble(txtHargaTanah.getText());
        double hargaBangunan = Double.parseDouble(txtHargaBangunan.getText());
        double dp = Double.parseDouble(txtDP.getText());
        int lamaCicilan = Integer.parseInt(txtCicilan.getText());


        // hitung total
        double hargaTotal = (luasTersedia * hargaTanahPerM2)
                            + hargaBangunan;
        double ppn = 0.10 * hargaTotal;
        double totalDenganPPN = hargaTotal + ppn;
        double cicilanBulan =
                (totalDenganPPN - dp) / lamaCicilan;

        // TAMPILKAN HASIL HITUNG
        txtHarga.setText(String.valueOf(hargaTotal));
        txtPPN.setText(String.valueOf(ppn));
        txtCicilanBulan.setText(String.valueOf(cicilanBulan));

        // decision tree C4.5
        double dpPersen =
                (dp / totalDenganPPN) * 100;
        String hasil;
        /*
            Aturan decision
            IF DP >= 20%
            AND Cicilan <= 120 bulan
            THEN disetujui
            ELSE ditolak
        */
        if (dpPersen >= 20 && lamaCicilan <= 120) {
            hasil = "DISETUJUI";
        } else {
            hasil = "DITOLAK";
        }
        // tampilkan hasil

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "HASIL DECISION TREE C4.5\n\n"
                + "DP (%) : " + String.format("%.2f", dpPersen) + "%\n"
                + "Lama Cicilan : " + lamaCicilan + " bulan\n\n"
                + "STATUS : " + hasil
        );

    } catch (NumberFormatException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Pastikan semua data angka diisi!",
                "ERROR",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_DecisiontreeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenjualanRumahForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenjualanRumahForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenjualanRumahForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenjualanRumahForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenjualanRumahForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Decisiontree;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnSimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JComboBox<String> cbArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JRadioButton rbTipe36;
    private javax.swing.JRadioButton rbTipe49;
    private javax.swing.JRadioButton rbTipe90;
    private javax.swing.JTextField txtCicilan;
    private javax.swing.JTextField txtCicilanBulan;
    private javax.swing.JTextField txtDP;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtHargaBangunan;
    private javax.swing.JTextField txtHargaTanah;
    private javax.swing.JTextField txtLuasAsli;
    private javax.swing.JTextField txtLuasTersedia;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPPN;
    // End of variables declaration//GEN-END:variables
}
